### ISSUE TITLE
皮肤无法使用

### ISSUE THREAD

**Issue by Yi-Xing** [zjhch123/solo-skin-emiya#20]
提示这个页面有错  "skins/emiya/footer.ftl" at line 11, column 65

**Comment by Yi-Xing** [comment]
> 提示这个页面有错 "skins/emiya/footer.ftl" at line 11, column 65

**Comment by zjhch123** [comment]
如果可以的话麻烦提供完整的错误记录哦。

皮肤需要搭配最新的solo使用

**Comment by Yi-Xing** [comment]
请问你能正常使用吗？我使用的就是最新版solo(v3.8.0)，报错信息如下：
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> miniPostfix  [in template "skins/solo-skin-emiya-master/footer.ftl" at line 11, column 67]
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
FTL stack trace ("~" means nesting-related):
&emsp;&emsp;- Failed at: ${miniPostfix}  [in template "skins/solo-skin-emiya-master/footer.ftl" at line 11, column 65]
&emsp;&emsp;- Reached through: #include "footer.ftl"  [in template "skins/solo-skin-emiya-master/macro-page.ftl" in macro "sidePage" at line 25, column 5]
&emsp;&emsp;- Reached through: @sidePage htmlTitle="${htmlTitle}" pa...  [in template "skins/solo-skin-emiya-master/macro-page.ftl" in macro "articlesPage" at line 31, column 3]
&emsp;&emsp;- Reached through: @articlesPage htmlTitle="${blogTitle}"  [in template "skins/solo-skin-emiya-master/index.ftl" at line 3, column 1]

        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:479) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.DollarVariable.accept(DollarVariable.java:63) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.visit(Environment.java:331) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.visit(Environment.java:337) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.include(Environment.java:2694) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Include.accept(Include.java:171) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.visit(Environment.java:367) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:872) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.invokeMacro(Environment.java:809) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.visit(Environment.java:367) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:872) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.invokeMacro(Environment.java:809) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.visit(Environment.java:331) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.visit(Environment.java:337) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.process(Environment.java:310) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.template.Template.process(Template.java:383) ~[freemarker-2.3.29.jar:2.3.29]
        at org.b3log.latke.http.renderer.AbstractFreeMarkerRenderer.genHTML(AbstractFreeMarkerRenderer.java:126) ~[latke-core-3.2.2.jar:?]
        at org.b3log.solo.processor.SkinRenderer.genHTML(SkinRenderer.java:86) ~[solo/:?]
        at org.b3log.latke.http.renderer.AbstractFreeMarkerRenderer.render(AbstractFreeMarkerRenderer.java:102) [latke-core-3.2.2.jar:?]
        at org.b3log.latke.http.Dispatcher.renderResponse(Dispatcher.java:126) [latke-core-3.2.2.jar:?]
        at org.b3log.latke.http.Dispatcher.handle(Dispatcher.java:98) [latke-core-3.2.2.jar:?]
        at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:84) [latke-core-3.2.2.jar:?]
        at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:38) [latke-core-3.2.2.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at org.b3log.latke.http.WebSocketHandler.handleHttpRequest(WebSocketHandler.java:94) [latke-core-3.2.2.jar:?]
        at org.b3log.latke.http.WebSocketHandler.channelRead0(WebSocketHandler.java:51) [latke-core-3.2.2.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.45.Final.jar:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by AlgerFan** [comment]
确实不能用了，最新版solo（3.80之后似乎又更新了），运行无报错，访问报错，完整报错信息如下：

```
[ERROR]-[2020-02-01 13:07:38]-[org.b3log.latke.http.renderer.AbstractFreeMarkerRenderer:108]: Renders template [index.ftl] failed [Request [
    method=GET,
    URI=/,
    contentType=null,
        remoteAddr=222.137.215.95,
    headers=[
        Host=www.algerfan.cn
        X-Real-IP=222.137.215.95
        X-Forwarded-For=222.137.215.95
        REMOTE-HOST=222.137.215.95
        Connection=close
        cache-control=max-age=0
        upgrade-insecure-requests=1
        user-agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
        sec-fetch-user=?1
        accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
        sec-fetch-site=none
        sec-fetch-mode=navigate
        accept-encoding=gzip, deflate, br
        accept-language=zh-CN,zh;q=0.9,en;q=0.8
        cookie=_ga=GA1.2.2094727851.1573347982; _ga=GA1.2.2094727851.1573347982; LATKE_SESSION_ID=H4W6ME7iM02SyYJJ; _gid=GA1.2.1156992008.1580484188; Hm_lvt_4281497bfb65c11d434048a736f3ec34=1578751252,1578877788,1578901563,1580484188; Hm_lpvt_4281497bfb65c11d434048a736f3ec34=1580484188; _gat=1; _gid=GA1.2.1156992008.1580484188; skin=Casper; mobile-skin=Casper; _gat_gtag_UA_129735490_2=1; visited=%5B%22%2Farticles%2F2018%2F12%2F11%2F1544469871012.html%22%2C%22%2Farticles%2F2020%2F01%2F11%2F1578739542414.html%22%2C%22%2Farticles%2F2020%2F01%2F06%2F1578296456011.html%22%2C%22%2Farticles%2F2019%2F03%2F06%2F1551868940012.html%22%2C%22%2Farticles%2F2018%2F11%2F18%2F1542474535012.html%22%5D; solo=55b3028feb62d660b22c9e0ac09972f66a7ef33f1e311eb60e19af3bdede4d6fc5c42b3aec74d4e6bd68e375ece5372f026caabe32b733090598056ec7e03be2; Hm_lpvt_4281497bfb65c11d434048a736f3ec34=1580486812
        content-length=0
    ]
]]
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> statistic.statisticPublishedBlogCommentCount  [in template "skins/Casper/footer.ftl" at line 46, column 15]
----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----
----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${statistic.statisticPublishedBlogCom...  [in template "skins/Casper/footer.ftl" at line 46, column 13]
        - Reached through: #include "footer.ftl"  [in template "skins/Casper/index.ftl" at line 38, column 1]
----
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:479) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.DollarVariable.accept(DollarVariable.java:63) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.visit(Environment.java:331) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.visit(Environment.java:337) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.include(Environment.java:2694) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Include.accept(Include.java:171) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.visit(Environment.java:331) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.visit(Environment.java:337) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.core.Environment.process(Environment.java:310) ~[freemarker-2.3.29.jar:2.3.29]
        at freemarker.template.Template.process(Template.java:383) ~[freemarker-2.3.29.jar:2.3.29]
        at org.b3log.latke.http.renderer.AbstractFreeMarkerRenderer.genHTML(AbstractFreeMarkerRenderer.java:126) ~[latke-core-3.2.2.jar:?]
        at org.b3log.solo.processor.SkinRenderer.genHTML(SkinRenderer.java:86) ~[solo/:?]
        at org.b3log.latke.http.renderer.AbstractFreeMarkerRenderer.render(AbstractFreeMarkerRenderer.java:102) [latke-core-3.2.2.jar:?]
        at org.b3log.latke.http.Dispatcher.renderResponse(Dispatcher.java:126) [latke-core-3.2.2.jar:?]
        at org.b3log.latke.http.Dispatcher.handle(Dispatcher.java:98) [latke-core-3.2.2.jar:?]
        at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:84) [latke-core-3.2.2.jar:?]
        at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:38) [latke-core-3.2.2.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at org.b3log.latke.http.WebSocketHandler.handleHttpRequest(WebSocketHandler.java:94) [latke-core-3.2.2.jar:?]
        at org.b3log.latke.http.WebSocketHandler.channelRead0(WebSocketHandler.java:51) [latke-core-3.2.2.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.45.Final.jar:4.1.45.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.45.Final.jar:4.1.45.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```

**Comment by AlgerFan** [comment]
@zjhch123 @Yi-Xing 原因已经找到并修改，已经提了 PR

**Comment by AlgerFan** [comment]
详情见 https://github.com/zjhch123/solo-skin-emiya/pull/21

**Comment by zjhch123** [comment]
非常奇怪，我这边solo 3.8.0是完全正常的，让我排查一下

**Comment by zjhch123** [comment]
不清楚为什么我这里是正常的，不过模板变量`miniPostfix`的确是不存在了，需要删掉。

PR里提到的文章目录无法正常显示我猜测是因为js文件没有压缩？我待会儿会更新一个版本，到时候可以再试试

**Comment by AlgerFan** [comment]
可以尝试更新一下镜像，3.8.0并不是最新的，应该还更新了

**Comment by AlgerFan** [comment]
目录的问题我也找不出来，刷新的时候会短暂出现“文章目录几个字”
![image](https://user-images.githubusercontent.com/38367204/73643520-9ff35680-46ae-11ea-90f1-c527cb61575b.png)

最新的docker镜像，原封不动的最新的皮肤：[演示链接](https://www.algerfan.cn/?skin=solo-skin-emiya2)

**Comment by zjhch123** [comment]
@AlgerFan 
你的jquery 500了，修复一下看看是不是这个的原因？

![image](https://user-images.githubusercontent.com/12215513/73647875-6115ce80-46b7-11ea-90f9-bc86eaf2e9cc.png)

**Comment by zjhch123** [comment]
查明原因了，solo更新导致部分资源的引用方式改变。<del>我待会儿提个pr修一下</del>

还有一个原因就是你目前用的最新镜像似乎没有release？我在solo库的[release page](https://github.com/88250/solo/releases)里看到的最新版本还是16天前的3.8.0？可不可以理解你现在在用的版本比较超前？

我不是很清楚版本应该跟随release走还是docker镜像走。**保险起见，暂时先不更新**

**Comment by AlgerFan** [comment]
@zjhch123 
jQuery我排查过，引入正常的jQuery（版本一致）也是一样：[演示链接](https://www.algerfan.cn/?skin=solo-skin-emiya3)

是的，实际上 docker 镜像的版本一直在迭代，因为是用定时器定时更新的，一段时间才会发布一个release

**Comment by AlgerFan** [comment]
这么说来，应该是版本的问题了，下一个版本再看看吧，实在找不到其他问题，引入正常的jQuery也是一样

**Comment by AlgerFan** [comment]
![image](https://user-images.githubusercontent.com/38367204/73821268-80833780-482e-11ea-805d-56514b50b60c.png)
应该就是资源的引用方式变了，我去提一个issue

**Comment by zjhch123** [comment]
> 这么说来，应该是版本的问题了，下一个版本再看看吧，实在找不到其他问题，引入正常的jQuery也是一样

嗯，现在看来似乎下个版本会有比较多的改动，等到下个版本发布之后我会根据更新说明也对皮肤做更新~

**Comment by AlgerFan** [comment]
> > 这么说来，应该是版本的问题了，下一个版本再看看吧，实在找不到其他问题，引入正常的jQuery也是一样
> 
> 嗯，现在看来似乎下个版本会有比较多的改动，等到下个版本发布之后我会根据更新说明也对皮肤做更新~

好的
